feat(index.js): adjust display date
liaojason2/justin-ramen-telegram-bot pull request #10
Opened 2022-09-26 09:41 UTC by yc97463

2022-09-26 10:09 UTC, pan93412 commented
這個語法或許可以讓實作更漂亮一點（雖然好像變長了 😂）

    today.toLocaleDateString('zh-tw', { day: 'numeric', month: 'numeric' })

---

<img width="605" alt="image" src="https://user-images.githubusercontent.com/28441561/192250755-127782a8-dd2f-4302-bc02-16e871484343.png">

2022-09-26 10:09 UTC, pan93412 reviewed
這個語法或許可以讓實作更漂亮一點（雖然好像變長了 😂）

    today.toLocaleDateString('zh-tw', { day: 'numeric', month: 'numeric' })

<img width="605" alt="image" src="https://user-images.githubusercontent.com/28441561/192250755-127782a8-dd2f-4302-bc02-16e871484343.png">

2022-09-26 17:46 UTC, liaojason2 requested changes

2022-09-26 17:51 UTC, liaojason2 commented
I don't think this a neccessary change, but @justinlin033 said whatever, so I think I can merge this PR after you fix your code. 

<img width="578" alt="Screen Shot 2022-09-27 at 1 48 07 AM" src="https://user-images.githubusercontent.com/46263348/192346090-0e172eeb-6843-4d55-832a-0554e9f6349f.png">

2022-09-27 03:20 UTC, yc97463 commented on index.js
> +      message = `${today.getMonth()+1}/${today.getDate()} ${time} 要吃拉麵嗎`;
Oops, I forgot to define `today`.

2022-09-27 12:09 UTC, liaojason2 commented on index.js
> +      message = `${today.toLocaleDateString('zh-tw', { day: 'numeric', month: 'numeric' })} ${time} 要吃拉麵嗎`;
Line length too long
https://eslint.org/docs/latest/rules/max-len

2022-09-27 12:09 UTC, liaojason2 requested changes

2022-09-27 12:09 UTC, liaojason2 commented on index.js
> +      message = `${today.toLocaleDateString('zh-tw', { day: 'numeric', month: 'numeric' })} ${time} 要吃拉麵嗎`;
Line length too long
https://eslint.org/docs/latest/rules/max-len

2022-09-27 12:51 UTC, liaojason2 approved these changes

2022-09-27 12:51 UTC, merged